name: LSUSB Self Test

permissions:
  contents: read

on:
  push:
    branches:
      - master
    paths:
      - lsusb
  pull_request:
    branches:
      - master
    paths:
      - lsusb

jobs:
  lsusb-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      
      - name: Test LSUSB
        run: ./lsusb
